export const data = {
  "Table 1 on Page 1": [
      [
          "FULL PAPER\nBritish Journal of Cancer (2018) 118, 181–188 | doi: 10.1038/bjc.2017.402"
      ],
      [
          "Keywords: radiological response; RECIST; sunitinib; progression-free survival; neuroendocrine tumour; pancreas"
      ]
  ],
  "Table 2 on Page 1": [
      [
          "British Journal of Cancer (2018) 118, 181–188 | doi: 10.1038/bjc.2017.402",
          ""
      ]
  ],
  "Table 1 on Page 2": [
      [
          "MATERIALS AND METHODS",
          null
      ],
      [
          null,
          ""
      ]
  ],
  "Table 1 on Page 3": [
      [
          "RESULTS",
          null
      ],
      [
          null,
          ""
      ]
  ],
  "Table 2 on Page 3": [
      [
          "DISCUSSION",
          null
      ],
      [
          null,
          ""
      ]
  ],
  "Table 1 on Page 4": [
      [
          "Table1.Baselinecharacteristicsofthepatientsincludedinouranalysis",
          null,
          null,
          null
      ],
      [
          "",
          "Allpatients(n=237)",
          "Sunitinibgroup(n=152)",
          "Controlgroup(Placebo;\nn=85)"
      ],
      [
          "Patientdemographics",
          null,
          null,
          null
      ],
      [
          "Ageatstudyentry(years)\nMedian(range)\nX65yearsold",
          "56(25–84)\n55(23%)",
          "56(25–84)\n32(21%)",
          "57(26–78)\n23(27%)"
      ],
      [
          "Gender\nMale(n(%))\nFemale(n(%))",
          "124(52%)\n113(48%)",
          "84(55%)\n68(45%)",
          "40(47%)\n45(53%)"
      ],
      [
          "Race\nWhite(n(%))\nBlack(n(%))\nAsian(n(%))\nOther(n(%))",
          "160(67%)\n4(2%)\n24(10%)\n49(21%)",
          "107(70%)\n4(3%)\n14(9%)\n27(18%)",
          "53(62%)\n0(0%)\n10(12%)\n22(26%)"
      ],
      [
          "ECOGPSatstudyentry\n0(n(%))\n1(n(%))\n2(n(%))",
          "129(54%)\n107(45%)\n1(1%)",
          "88(59%)\n64(42%)\n0(0%)",
          "41(48%)\n43(51%)\n1(1%)"
      ],
      [
          "Functioningtumour\nYes(n(%))\nNo(n(%))\nUnknown(n(%))",
          "104(44%)\n132(55%)\n1(1%)",
          "63(41%)\n88(58%)\n1(1%)",
          "41(52%)\n44(48%)\n0(0%)"
      ],
      [
          "Firstdiagnosis Z3yearsbeforeinclusionintrial\nYes(n(%))\nNo(n(%))\nUnknown(n(%))",
          "103(43%)\n133(56%)\n1(1%)",
          "55(36%)\n96(63%)\n1(1%)",
          "48(56%)\n37(44%)\n0(0%)"
      ],
      [
          "Previoussystemictreatment(excluding SSA)\nYes(n(%))\nNo(n(%))",
          "135(57%)\n102(43%)",
          "85(56%)\n67(44%)",
          "50(59%)\n35(41%)"
      ],
      [
          "Issunitinib/placebo3rdlineoftreatmentormore\n(excluding SSA)?\nYes(n(%))\nNo(n(%))",
          "70(30%)\n167(70%)",
          "45(30%)\n107(70%)",
          "25(29%)\n60(71%)"
      ],
      [
          "Doseofsunitinib/placebo\n37.5mgod\n50mgod(4þ2)",
          "171(72%)\n66(28%)",
          "86(57%)\n66(43%)",
          "85(100%)\n0(0%)"
      ],
      [
          "Patientoutcomes",
          null,
          null,
          null
      ],
      [
          "Follow-up,median(range)\nPFS(estimatedmedian KM)a,median(95%CI)\nEvents PFS,yes(n(%))\nFree-ofprogressionat11months,yes(n(%))\nMediantimeontreatment(months),median(range)\nBestradiologicalresponse(definedbylocal\ninvestigator)a\nPartialresponse(n(%))\nStabledisease(n(%))\nProgressivedisease(n(%))\nIndeterminate(n(%))\nBestchangeinsumofmarkerlesions(%)b,median\n(range)\nTimeofscanwithbest-responseb,median(range)\nNumberofscansavailableb,totalnumber",
          "16.5(0.1–80.6)\n7.7(95%-CI7.1–9.3)\n112(47%)\n32(14%)\n5.1(0–20.1)\n19(8%)\n150(63%)\n35(15%)\n33(14%)\n-5.7(-100–43.3%)\n1(1–17)\n788",
          "15.6(0.1–80.3)\n9.3(95%CI7.6–12.2)\n63(41%)\n27(18%)\n6.4(0.4–19.7)\n19(13%)\n101(66%)\n14(9%)\n18(12%)\n-12.8(-100–36.4)\n3(1–17)\n535",
          "23.2(0.1–80.6)\n5.4(3.5–6.01)\n49(58%)\n5(6%)\n3.7(0–20.1)\n0(0%)\n49(58%)\n21(25%)\n15(17%)\n1.7(-46.7–43.3)\n1(1–13)\n253"
      ],
      [
          "Abbreviations: ECOG-PS=Eastern Cooperative Oncology Group performance status; KM=Kaplan–Meier estimation; n=number of patients; PFS=progression-free survival; SSA=\nsomatostatinanalogue.\na Asdefinedbylocalinvestigator.\nb Aspercalculationsperformedinthisposthocanalysis.",
          null,
          null,
          null
      ]
  ],
  "Table 1 on Page 5": [
      [
          "Table2.Identificationofthemostinformativetime-pointemploying ROCcurveanalysis(AUC)andlogisticregressionfor",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "predictionofprogression-freeat11months",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "ROCanalysis Logisticregression ROCcurvecomparisonanalysis",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "Time-point",
          "Numberof\nobservations",
          "AUC(95%CI)",
          "Logistic Regression\nOR(95%CI)",
          "Logistic Regression\nP-value",
          "AUC(95%CI)",
          "Numberof\nobservation"
      ],
      [
          "Bestresponse",
          "144",
          "0.77(0.67–0.86)",
          "1.05(1.02–1.07)",
          "o0.001",
          "0.66(0.53–0.79)a",
          "68"
      ],
      [
          "Month1",
          "134",
          "0.67(0.54–0.78)",
          "1.05(1.01–1.1)",
          "0.011",
          "Notincluded",
          "—"
      ],
      [
          "Month2",
          "68",
          "0.57(0.43–0.72)",
          "1.01(0.98–1.04)",
          "0.489",
          "Notincluded",
          "—"
      ],
      [
          "Month3",
          "107",
          "0.60(0.48–0.74)",
          "1.02(1.01–1.04)",
          "0.037",
          "Notincluded",
          "—"
      ],
      [
          "Month5",
          "79",
          "0.76(0.65–0.86)",
          "1.04(1.02–1.06)",
          "0.001",
          "0.74(0.62–0.86)a",
          "68"
      ],
      [
          "Month7",
          "54",
          "0.78(0.66–0.9)",
          "1.05(1.01–1.08)",
          "0.002",
          "0.75(0.63–0.86)a",
          "68"
      ],
      [
          "Month9",
          "38",
          "0.73(0.54–0.91)",
          "1.04(0.99–1.1)",
          "0.078",
          "Notincluded",
          "—"
      ],
      [
          "Month11",
          "24",
          "0.64(0.26–1)",
          "1.02(0.98–1.06)",
          "0.370",
          "Notincluded",
          "—"
      ],
      [
          "Month13",
          "18",
          "0.49(0.1–0.96)",
          "0.99(0.97–1.02)",
          "0.553",
          "Notincluded",
          "—"
      ],
      [
          "Month15",
          "8",
          "0.60(0–1)",
          "0.98(0.94–1.03)",
          "0.496",
          "Notincluded",
          "—"
      ],
      [
          "Month17",
          "2",
          "—",
          "—",
          "—",
          "Notincluded",
          "—"
      ],
      [
          "Month19",
          "2",
          "—",
          "—",
          "—",
          "Notincluded",
          "—"
      ],
      [
          "Month21",
          "1",
          "—",
          "—",
          "—",
          "Notincluded",
          "(cid:2)"
      ],
      [
          "Abbreviations:AUC=areaunderthecurve;CI=confidenceinterval;OR=oddsratio;ROC=receiveroperatingcharacteristic.\na Chi-square P-value0.3733(Supplementary Figure3).",
          null,
          null,
          null,
          null,
          null,
          null
      ]
  ],
  "Table 2 on Page 5": [
      [
          "Table3.Identificationofalternativecut-offsfordefinitionof\n‘partialresponse’employingdatafromthe54scansavailable",
          null,
          null,
          null,
          null
      ],
      [
          "atmonth7",
          null,
          null,
          null,
          null
      ],
      [
          "Cut-\noff",
          "Sensitivity",
          "Specificity",
          "Correctly\nclassified\npatients(%)",
          "Numberofpatients\nclassifiedas\nresponsewhenthis\ncut-offisemployed\ntothebest-response\nassessmenta"
      ],
      [
          "(cid:2)30%",
          "31%",
          "96%",
          "64.8%",
          "29(20%)"
      ],
      [
          "(cid:2)20%",
          "39%",
          "89%",
          "64.8%",
          "51(35%)"
      ],
      [
          "(cid:2)15%",
          "46%",
          "86%",
          "66.7%",
          "61(42%)"
      ],
      [
          "(cid:2)10%",
          "50%",
          "82%",
          "66.7%",
          "84(59%)"
      ],
      [
          "a Aspercalculationsperformedinthisposthocanalysis.",
          null,
          null,
          null,
          null
      ]
  ],
  "Table 1 on Page 6": [
      [
          "Table4.Survivalanalyses:median PFSestimations(Kaplan–Meiermethod)andunivariateandmultivariable Coxregression",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "analyses",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "Univariateanalysis(bytypeoftreatmentandresponse)",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "Sunitinib-treated\npatients",
          "Variable",
          "Group",
          "Median PFSinthe\nrespondinggroup\n(months)(KM)",
          "Median PFSinthenon-\nrespondinggroup(months)",
          "Univariate COX(HR95%\nCI)",
          "Univariate\nCOXP-value"
      ],
      [
          "Allpatientstreated\nwith Sunitinib\n(n=144)",
          "Best-response\ncut-off",
          "(cid:2)30%\n(cid:2)10%",
          "12.23(8.32–14.99)\n10.98(8.28–12.71)",
          "8.28(7.10–12.49)\n7.63(6.54–12.92)",
          "0.69(0.38–1.22)\n0.55(0.31–0.97)",
          "0.198\n0.040"
      ],
      [
          "Phase IIIpatients\ntreatedwith\nSunitinib(n=80)",
          "Best-response\ncut-off",
          "(cid:2)30%\n(cid:2)10%",
          "13.60(7.49-nr)\n13.60(7.39-nr)",
          "10.15(7.19-nr)\n6.01(2.10-nr)",
          "0.68(0.28–1.62)\n0.33(0.15–0.72)",
          "0.386\n0.005"
      ],
      [
          "Phase IIpatients\ntreatedwith\nSunitinib(n=64)",
          "Best-response\ncut-off",
          "(cid:2)30%\n(cid:2)10%",
          "10.98(7.79–14.99)\n9.30(7.10–12.23)",
          "7.63(6.61–12.26)\n7.63(6.54-nr)",
          "0.48(0.21–1.13)\n1.01(0.42–2.43)",
          "0.093\n0.980"
      ],
      [
          "Placebo-treated\npatients",
          "Variable",
          "Group",
          "Median PFSinthe\nrespondinggroup\n(months)",
          "Median PFSinthenon-\nrespondinggroup(months)",
          "Univariate COX(HR95%-CI)",
          "Univariate\nCOXP-\nvalue"
      ],
      [
          "Phase IIIpatients\ntreatedwith Placebo\n(n=76)",
          "Bestresponse\ncut-off",
          "(cid:2)30%\n(cid:2)10%",
          "Nr(nr-nr)\n9.63(9.63-nr)",
          "5.42(3.38–6.01)\n3.84(3.38–5.65)",
          "0.59(0.08–4.43)\n0.30(0.09–0.99)",
          "0.616\n0.050"
      ],
      [
          "Univariate/multivariableanlaysis(bytypeoftreatmentandresponse)",
          null,
          null,
          null,
          null,
          null,
          null
      ],
      [
          "Variable",
          "Group",
          "Median PFS\n(months)KM",
          "Univariate COX-regression",
          null,
          "Multivariable COX-Regression(n=220)",
          null
      ],
      [
          "",
          "",
          "",
          "HR(95%CI)",
          "P-value",
          "HR(95%-CI)",
          "P-value"
      ],
      [
          "Treatment",
          "Placebo\nSunitinib",
          "5.42(3.48–6.01)\n9.30(7.63–12.26)",
          "1(Ref.)\n0.43(0.29–0.62)",
          "(cid:2)\no0.001",
          "1(Ref.)\n0.56(0.36–0.89)",
          "(cid:2)\n0.014"
      ],
      [
          "Classicalcut-off\n(30%)",
          "No\nYes",
          "7.39(6.01–8.27)\n11.97(9.27–14.99)",
          "1(Ref.)\n0.56(0.34–0.93)",
          "(cid:2)\n0.026",
          "1(Ref.)\n0.95(0.52–1.75)",
          "(cid:2)\n0.877"
      ],
      [
          "Alternative Cut-off\n(10%)",
          "No\nYes",
          "5.85(3.98–7.39)\n10.99(8.32–12.2)",
          "1(Ref.)\n0.42(0.28–0.62)",
          "(cid:2)\no0.001",
          "1(Ref.)\n0.57(0.34–0.97)",
          "(cid:2)\n0.038"
      ],
      [
          "Abbreviations:CI=confidenceinterval;ECOGPS=Eastern Cooperative Oncology Group Performance Status;HR=hazardratio;KM=Kaplan–Meierestimation;n=numberofpatients;\nNR=notreached;PFS=progression-freesurvival;Ref.=referencecategory.",
          null,
          null,
          null,
          null,
          null,
          null
      ]
  ],
  "Table 1 on Page 7": [
      [
          "REFERENCES",
          null
      ],
      [
          null,
          ""
      ]
  ],
  "Table 2 on Page 7": [
      [
          "ACKNOWLEDGEMENTS",
          null
      ],
      [
          null,
          ""
      ]
  ],
  "Table 3 on Page 7": [
      [
          "CONFLICT OF INTEREST",
          null
      ],
      [
          null,
          ""
      ]
  ]
}
